### This Notebook check if a GPU is available and CUDA is configured in the environment

In [1]:
import torch

In [2]:
# test if GPU is available
# this code is OK only for a single GPU... see other NOtebooks for multiple GPU environments

if torch.cuda.is_available():
    print('GPU (cuda) is available!')
    print('The GPU type is:',torch.cuda.get_device_name(0))
    
    device = torch.device("cuda") 
else:
    print('GPU (cuda) is not available!')
    
    device = torch.device("cpu")

GPU (cuda) is not available!


In [3]:
print('The available device is:', device)

The available device is: cpu


In [4]:
# this code now can be used to move tensor on the device correctly if GPU is available

t1 = torch.tensor([[1,1], [2,2]])

t1 = t1.to(device)

t1

tensor([[1, 1],
        [2, 2]])

In [5]:
t1

tensor([[1, 1],
        [2, 2]])

In [6]:
# to get the numpy array:

t1.numpy()

array([[1, 1],
       [2, 2]])